### ISSUE TITLE
[Graphics Request] My own take on a modern Mario sprite?

### ISSUE THREAD

**Issue by WinslowJosiah** [Coolcord/Level-Headed#15]
I love this randomizer so far, and although I know that adding new graphics packs / player sprites isn't your focus, I would still like to submit some sprites from my own hack for your consideration.

The graphics pack as a whole is incomplete, but I think it looks cool. I think the Mario sprite especially would be a nice addition to the randomizer. It's a different sort of "modern Mario" sprite than any of the others that are available.

I've also made a few small changes to the ASM, including something that might be useful for the randomizer: a 2-digit lives display. It works for as many as 137 lives (more than the base game lets you have), could be a useful patch for those who want it, and fits in the same space as the original code (at offset 0x084f in the ROM, replace the next 15 bytes with `E8A838E90A10F9CA8AF0038D08038C`).

However, one thing to keep in mind about that lives-counter code is that it reports the number as-is, so the lives counter appears off by one. (My hack adds 1 to your starting lives counter to compensate, and it changes code such that having 0 in the lives counter gives you game-over, instead of a negative number in the lives counter.)

The IPS patch for my whole hack is [here](https://gofile.io/?c=5BSMbG), if you wanna take a look.

![gif](https://user-images.githubusercontent.com/54851915/75561430-9ee2ea00-5a0c-11ea-966d-951fe5548665.gif "New Old Super Mario Bros")

**Comment by Coolcord** [comment]
Visually, this looks great! The art style is unique and I'd be more than happy to include it if possible!

However, I might have to rearrange many of the tiles in the patch so that it's compatible with other patches that already exist in Level-Headed. I have been trying to keep the tile layout of sprites to be similar or close to the original. This helps reduce conflicts when using the graphics combiner, custom power-ups, and some custom enemy behaviors. From a quick glance, it doesn't look like this will be an issue with your patch or sprites, but this issue is generally what requires the most labor on my end.

As far as the assembly goes, Level-Headed already has some patches that address the double digit lives counter and limit lives to 99. The code for that can be seen [here](https://github.com/Coolcord/Level-Headed/blob/c759fef63d6600fa3fba5e539297260c9b87f754/SMB1/SMB1_Writer/Hacks.cpp#L150) if you're curious.

When I can get some more free time, I'll look into the tile layout further and let you know if it looks feasible for me to include. If it gets included, what would you like the graphics pack to be called? Also, what name would you like to be credited under?

**Comment by WinslowJosiah** [comment]
Ah, you _do_ have a 2-digit lives patch. I haven't gotten a 2-digit lives count while playing around yet, so I didn't know.

And yes, I have rearranged a bunch of the Mario tiles, and saved tile space wherever possible. I wanted to put in the peace-sign pose when starting levels and going down pipes, which I _almost_ succeeded at...there's one edge case I was never able to fix. (I wonder if that pose could be added somehow...but I doubt it.) My Mario animations take fewer tiles than before - 70 vs 93 - and I've reduced other tiles wherever possible, so I don't see that being much of an issue.

If it gets included, I'd like to be credited as Josiah Winslow. I dunno what to call it...maybe something like "New Mario", or "Modern Mario", but that's not entirely apt. Up to you, I guess!

**Comment by Coolcord** [comment]
These graphics will be included both as a graphics pack (simply called "Josiah Winslow") and as a player sprite (called "Josiah Winslow's Mario") in the next update (v0.3.6). You can review the commit [here](https://github.com/Coolcord/Level-Headed_Data/commit/ccd4064aa11df8bfe1518a8adcfae5fe32723412) if you'd like.

Unfortunately, I had to remove the peace-sign pose as it had compatibility issues with some custom powerups (likely due to the Fire Flower/Starman flashing code being overwritten). Other than that, it seems to work great so far with the other graphics packs.

If you want to try out Level-Headed with your graphics before v0.3.6 comes out, you can pack a new Graphics.sa file with [SAM](https://github.com/Coolcord/Sequential_Archive/releases) using the Graphics folder from [here](https://github.com/Coolcord/Level-Headed_Data/), then copy the new Graphics.sa file into Level-Headed's Data/SMB1 folder. Alternatively, you can [compile Level-Headed from source](https://github.com/Coolcord/Level-Headed/wiki/Compiling-Level%E2%80%90Headed-via-the-Unix-Build-Script).

Thanks for your contribution!

**Comment by WinslowJosiah** [comment]
Believe me, the peace sign pose was hard enough to patch in on my end. I'm okay with it being left out.

Thank you for including my Mario and graphics pack!

**Comment by WinslowJosiah** [comment]
By the way, I'm testing out the Josiah Winslow graphics pack, and it seems that Lakitu doesn't throw Spiny Eggs, but full-grown Spinies? Is this some sort of compatibility issue I'm not aware of?

**Comment by Coolcord** [comment]
I still need to write some documentation on this feature, as I haven't gotten around to it yet. That's likely the spiny egg behavior that was selected (probably randomly selected). There's 6 different behaviors for spiny eggs: Bounce, Chase Mario, Do Not Break, Explode Into Flames, No Eggs, and Normal. If everything's working correctly, the game you generated probably picked "No Eggs". The settings available to the generator depend on the current difficulty setting, but you can change it manually by creating a custom difficulty.

From what I tested, everything with Lakitus worked fine except for "Explode Into Flames", but that behavior tends to need a compatibility fix anyway. There's a fix for "Explode Into Flames" [here](https://github.com/Coolcord/Level-Headed_Data/blob/master/Graphics/Fixes/Graphics%20Pack/Spiny%20Eggs%20Explode%20Into%20Flames/Josiah%20Winslow.hexp), but you probably already have it if you packed the Graphics folder from [here](https://github.com/Coolcord/Level-Headed_Data) or if you compiled from source.

Let me know if you run into any other issues.
