### ISSUE TITLE
bullet bill launchers can be pointed at checkpoints

### ISSUE THREAD

**Issue by madewokherd** [Coolcord/Level-Headed#16]
I played a seed today which had a checkpoint with a bullet bill launcher on the same screen pointed at it. This results in an almost immediate death if you don't jump.

I don't know if this is considered a "bug", but I wanted to report it just in case.

**Comment by Coolcord** [comment]
Thanks for reporting this! It's a good find!

I went ahead and added a new pass to the level generator that will fix the problem. It scans the level for Bullet Bill cannons, and if any ground level cannons are found on the first page or on the midpoint page, they're replaced with vertical blocks.

[This new fix](https://github.com/Coolcord/Level-Headed/commit/1c7a4e1a86fa611b4fe2cfc6a5ff76468821daab) will be available in the next update. Since there have been a number of little bug fixes like this, I'll probably release a v0.3.9 at some point, as v0.4 is still a ways off.
