### ISSUE TITLE
How can I make level scripts?

### ISSUE THREAD

**Issue by stvene3004** [Coolcord/Level-Headed#19]
I saw the files of the level scripts for creating a second quest and I wonder if you can tell me how I can make one of those. It'd be cool if you can add this to the wiki.

**Comment by Coolcord** [comment]
There's actually a [wiki page for this already](https://github.com/Coolcord/Level-Headed/wiki/How-to-Create-Your-Own-Levels-with-the-SMB1_Compliance-Format), though it might be outdated in some areas.

I'd recommend starting with a copy of the original levels so that you can get an idea of how the level scripts work. These can be found under "./Levels/SMB1/Super Mario Bros. 1 (Modified Original Levels).lvls" in the folder where you installed Level-Headed. You'll need to unpack them with [SAM](https://github.com/Coolcord/Sequential_Archive/releases) to modify the scripts, then repack them when you're ready to use them with Level-Headed. Make sure to save the repacked archive with the ".lvls" extension!

**Comment by jaxon19** [comment]
idk
