### ISSUE TITLE
[Feature Request] Option to always restart on game over on the current world by default (without A+Start)

### ISSUE THREAD

**Issue by macobra52** [Coolcord/Level-Headed#21]
I know it is a simple trick, but I feel the option would be nice to have so that you don't have to worry about doing the combination at all or risk messing up the input. It would be similar in behavior to All-Stars SMB1 as well.

**Comment by Coolcord** [comment]
I can implement this fairly easily, but there's a catch: once you beat the game, you'll always start at the last world in the game. This will happen until the game is reset. After the game is reset, the player will start at World 1 once again. As far as I can tell, this is the default behavior of the A+Start code anyway. Fixing this would require adding more ASM into the game, which I'm out of space for as far as universal hacks go.

What do you think? Are you okay with that behavior?

The checkbox to enable this option will only be available when the user has set a specified number of lives for a game. It won't be available when either Infinite Lives or Permadeath are selected.

**Comment by macobra52** [comment]
That works for me. From a racing perspective generated games would only be played once anyway.

**Comment by Coolcord** [comment]
This feature has now been implemented as of [this commit](https://github.com/Coolcord/Level-Headed/commit/729c506fabf436f1934057bc602c5f7af186da60) and will be available in the next release of Level-Headed! The option will not be available in partially supported games, since as far as I can tell, the Co-op ROM does not make use of the A+Start Continue code.
