### ISSUE TITLE
Game freezes when shooting an enemy with Luigi's Fire Flower

### ISSUE THREAD

**Issue by macobra52** [Coolcord/Level-Headed#24]
Using the latest version of Level-Headed (0.3.9), I generated three different games with all of them having the Powerup set to Luigi's Fire Flower (config settings for the last one are below if needed). In all three shooting an enemy with a green fireball freezes the game once it makes contact. I'm using Nestopia UE and generating with a clean SMB1 rom.

[SMB1_Compliance_To_SMB1.txt](https://github.com/Coolcord/Level-Headed/files/6619090/SMB1_Compliance_To_SMB1.txt)

**Comment by Coolcord** [comment]
Thanks for reporting this! It was a good find!

Apparently, there was an incompatibility between Spiny Eggs Explode Into Flames + Swimming Mushroom + Fire-based powerups. When all three were used at once, the swimming mushroom assembly would overwrite some important enemy kill code, causing the crash. I wrote a [fix for this](https://github.com/Coolcord/Level-Headed/commit/0477c09ccb183f1fd11c72320e9ac8482c2ecf93) so that this combination of settings will be possible again.

Since this is a game crasher, I'll release a v0.3.9-1 update to address the issue when I can get the time. I can't give an ETA on when I'll have time to release this update, so for now, I'd recommend avoiding this specific combination of settings (either use a different powerup, disable the swimming mushroom, or change the spiny egg behavior to something else). Alternatively, you can always use this fix now by [compiling Level-Headed's source code](https://github.com/Coolcord/Level-Headed/wiki/Compiling-Level%E2%80%90Headed-via-the-Unix-Build-Script).

**Comment by macobra52** [comment]
Wow. I would not have guessed that specific combination. I did try one game with vanilla fireballs and it worked correctly, but I guess it was because the egg behavior was different (had it set to Random (No Bounce)), not due to the Luigi fireballs specifically.

Thanks for the quick fix!
