### ISSUE TITLE
[Bug] When autoscroll is enabled in a level that would have flying Cheep Cheeps, it spawns offscreen Bullet Bills.

### ISSUE THREAD

**Issue by OopityDoop** [Coolcord/Level-Headed#28]
The only problem with this is the Bullet Bills still spawn if they are disabled for the level type in question. This problem doesn't happen if Autoscroll + Flying Cheep Cheeps is enabled.

**Comment by Coolcord** [comment]
Thanks for the bug report! However, this actually isn't a bug and is working as intended.

The hardest levels Level-Headed can create tend to be Auto Scrolling Levels with Flying Cheep-Cheeps. To accommodate for this, the "Auto Scroll + Flying Cheep-Cheeps" setting was added. This option allows Flying Cheep-Cheeps to spawn in Auto Scrolling levels only after a certain difficulty threshold has been met. If this threshold has not been met, the Flying Cheep-Cheeps are downgraded to Off-screen Bullet Bills. This is because Off-screen Bullet Bills are much easier for the player to dodge.

**This setting will always ignore the Off-screen Bullet Bills setting for that level type, as a continuous enemy spawner of some sort was requested.** The difficulty presets have been balanced around this idea.

Thanks for the interest in Level-Headed!
