### ISSUE TITLE
MMC3 ROM mapper expansion opportunity for SMB1

### ISSUE THREAD

**Issue by Alucard648** [Coolcord/Level-Headed#3]
I found a ROM patch that converts SMB1 ROM to MMC3, thus allowing to expand ROM and get more space for levels. Details, the patch and ReadMe can be found here:
http://www.romhacking.net/hacks/2432
Any opinion?

**Comment by Coolcord** [comment]
This could be useful in the future. However, I'm thinking about pushing users to generate more smaller games rather than one large game. Right now, if a user creates 2 games that are 4 worlds long, the quality of the levels turn out much better than a long 7 world game. This patch could fix that problem if I want to put the time into adding support for it, but as it stands now, I'm the only person working on this project.

For now, it is recommended to generate 4 world games. Future releases of Level-Headed will likely limit the max world count to something like 4 or 5, but I'll add support to make multiple games in one pass.

What needs to be the highest priority for this level generator at this point in development is more patterns. Right now, the levels feel rather similar, so I need to put what time I have towards that effort.

Thanks for the suggestion!

**Comment by Alucard648** [comment]
I am hoping there would be custom pattern editor for faster pattern making.

**Comment by Coolcord** [comment]
If I can get the time to write a custom pattern editor, it'll happen.
