### ISSUE TITLE
Hammer Bro Placement.

### ISSUE THREAD

**Issue by AnonymousIdeas** [Coolcord/Level-Headed#5]
Hammer bros often spawn inside walls in the castle levels when the walls go really low, and in other levels they seem to spawn in mid air and just fall to the bottom. I think this is due to they are just replacing other enemies, and i'm not sure how you would fix it, but I just thought I'd let you know. Otherwise I haven't found any issues.

**Comment by Coolcord** [comment]
Thanks for the bug report!

There was a bug with the level crawler that would cause enemies to sometimes spawn inside of walls of castle levels. That's been fixed, and the patch will be included in v0.3.0. In SMB1, hammer bros would often jump as soon as they spawn, which is why it looks like they're spawning in air. It's a quirk of the original engine that I don't plan to address.

As you stated, "Hammer Time" simply replaces about 1 in 5 enemies with a hammer bro, but their spawn coordinates don't change and the levels aren't designed around them. Starting with v0.2.2, "Hammer Time" is automatically enabled for the last ~20% of the game to increase the difficulty.

The future of "Hammer Time" mode is still a little uncertain. Originally, it was supposed to just be a quick, gimmicky challenge mode that would be removed once proper level design patterns that included hammer bros were added. As it stands now, I don't think I'll remove it, but it may end up disabled by default in the future.

**Comment by AnonymousIdeas** [comment]
Alright! Glad to see this interesting project progress :)
