### ISSUE TITLE
Impossible level generated.

### ISSUE THREAD

**Issue by ghost** [Coolcord/Level-Headed#6]
When experimenting with with version 0.3-RC2 of the Randomizer, I encountered a level with a jump that is impossible to complete if you are not at least Super / Big Mario, in World 1-3. Standard SMB1 course design requires that all levels should be able to be completed as Regular / Small Mario. The brick block ceiling over this jump makes that impossible.

![fail](https://user-images.githubusercontent.com/24427487/43283953-5cc99842-90e8-11e8-959c-5160bc9c34a9.png)

Enclosed is the generated level script. (*I added `.txt` to the extension so GitHub would let me upload it here*)
[Random 18-07-26-14-49-25-272.lvls.txt](https://github.com/Coolcord/Level-Headed/files/2233317/Random.18-07-26-14-49-25-272.lvls.txt)

**Comment by Coolcord** [comment]
Thanks for the bug report! It's a good find!

I've decided to decrease the max hole length by 1, which should also have the side affect of having less massive jumps (which I was thinking about changing anyway). With the [bug fix](https://github.com/Coolcord/Level-Headed/commit/bd590cb1b4aad7e5a60ee2f0eb9cf361988fc72a), this scenario can still happen, but now it's actually possible (although you'll have to be very precise with your jump to get through it).

With this change, I think a Release Candidate 3 will be necessary, as this could affect a lot of other things.

Thanks for testing!

**Comment by ghost** [comment]
You're welcome, and thanks for making this! I'm having fun so far. The long jumps seem fun though, when possible, so perhaps this rule should only apply to Underground levels (*due to the ceiling*). Another alternative could be to add a hidden block somewhere (*perhaps near that one tile lip*) to help make the jump completable (*which is rather common in SMB2J aka Lost Levels*).

**Comment by Coolcord** [comment]
I was considering limiting it to only Underground levels. However, there were some brutal long jumps where immediately after there would be an enemy (or worse, a hammer bro), and the player would be left blind to what's coming. Those scenarios were mostly possible from what I've seen, but very unfair. I'm hoping that this patch might also make that scenario less common as it seemed to happen a lot with the large jumps, almost guaranteeing a death the first time around.

This is mostly due to SMB1's limited relative coordinate system, so enemies can't be placed very far apart from one another. The generator tries to only place them on ground, but if there's no ground for a while, it'll end up placing them near a hole, as it'll have no other choice.

The max hole length is still 7 blocks long, which requires a pretty good running start anyway.
