### ISSUE TITLE
Games freezes when moving backwards at a certain point in World 2-3

### ISSUE THREAD

**Issue by ghost** [Coolcord/Level-Headed#9]
When testing games generated with both 0.3-RC2 and 0.3-RC3, I've experienced game crashes in World 2-3 triggered by moving backwards beyond a certain point that I have yet to determine. I'm not sure what the cause is, nor am I sure if it's a Level-Headed bug or an emulation. The emulator used was the latest FCEUMM core in RetroArch 1.7.3.

![img_20180727_185014215](https://user-images.githubusercontent.com/24427487/43352406-fc11b07a-91f0-11e8-86c1-acf62cc18ced.jpg)
![img_20180727_222729024](https://user-images.githubusercontent.com/24427487/43352407-fc2c66d6-91f0-11e8-9d81-1f019d357a59.jpg)

When the freeze occurs, the HUD shifts far to the left.

Enclosed is the level file generated.

[Random 18-07-27-21-44-49-278.lvls.txt](https://github.com/Coolcord/Level-Headed/files/2237642/Random.18-07-27-21-44-49-278.lvls.txt)

**Comment by Coolcord** [comment]
If I had to guess, this may be a bad music patch and tone color combination, as that would explain why it would crash while jumping on a paratroopa while collecting a coin.

Do you remember what music patch and/or tone color was used? If not, if you still have the ROM, could you upload a patch for me with the bug in it? A .hexp (Hexagon patch) file would be the best here, as it's plain text, but you can also use an .ips patch if that's easier.

**Comment by ghost** [comment]
I still have the ROMs it generated, yes. As for which music patch / tone color used. The ROM in the first photo was sent to random iirc, so I don't know what it picked.

*****

As for the 2nd photo, that was the only one I generated with the RC3 build, so I still have those settings:

**Graphics:** `Super Mario Bros. DX v3.4 (by flamepanther)`
**Music:** `Flower Mario (by Garuna)`
**Tone:** `Random`

I have no clue how to turn what the generator made into a patch. You'd have to walk me through that.

**Comment by Coolcord** [comment]
[Download Hexagon](https://github.com/Coolcord/Hexagon)

When you run the program, under the Patch tab, click "Create Patch". It'll prompt you for the original file, so give it the base ROM you used (e.g. "Super Mario Bros. (JU) (PRG0) [!].nes"). Next it'll ask you for a modified file, so give it the generated ROM.

After this, a .hexp file should be generated, which can be uploaded here.

**Comment by ghost** [comment]
I used Hexagon and generated the requested files. I hope this helps, sorry for the late response.
[Randomizer_HexagonPatches.zip](https://github.com/Coolcord/Level-Headed/files/2238317/Randomizer_HexagonPatches.zip)

*Note: The source ROM used is from the 2017 No Intro set to ensure quality, Hexagon displays this as `Super Mario Bros. (World)`, which Level-Headed identifies as `Super Mario Bros. (JU) (PRG0) [!]`*

**Comment by Coolcord** [comment]
Perfect, thanks!

With this, I was able to replicate the crash. I'll look into what's causing it.

**Comment by Coolcord** [comment]
So this bug was a really good find on your part! It's actually an issue with how I'm injecting my bouncy spiny eggs ASM code. There's a branch after the injection that tries to run code that was overwritten, hence the crashes.

Fixing the ASM code won't be a problem, but the new code takes up a few more bytes. Unfortunately, I've completely ran out of free space in the ROM, and I don't plan to support expanded ROMs, so we have a few options here:

1.  Drop the seconds timer speed completely. This would free up enough space. When I put out RC1, people didn't seem too happy with the real time timer, and I actually got a few messages asking for a way to turn it off. An option to disable it was added in RC2. However, a single timer speed needs to be decided on in the future, as I would like for the generator to do something with the time later.
2.  Make bouncy spiny eggs a "complimentary hack". This would mean that bouncy spiny eggs couldn't appear in the same game as auto scrolling levels or fire bros, but we could keep the real time timer.
3.  Keep the real time timer, but drop the ASM code that changes the check value from 100 to 40. This means that the music would be playing fast for about 2.5x longer than it normally would when the seconds timer speed is used.

Personally, I'm leaning towards 1, as it would solve two problems at once and allow for more variety in a single game. What do you think? Do you care about the timer speed?

**Comment by ghost** [comment]
Option 1 sounds good. I prefer the classic timer speed anyways.

**Comment by Coolcord** [comment]
K, I'll do that then. Most people seem to like that speed, so I'll make that the target speed from now on.

**Comment by ghost** [comment]
Unrelated, but can we get horizontally flying green paratroopas? I miss those. I loved seeing them on the bridge levels.

**Comment by Coolcord** [comment]
Those types of paratroopas are weird, as I believe that they can fly through walls, but I don't think that'll be a big deal. I have a level type in mind that I plan to use them on a lot.

For bridge levels, I'll write down the idea and consider implementing it in the next feature update (maybe v0.3.1?). It might be a good idea for them to be tied to their own difficulty rating.

I don't know what other enemies do when they bump into them though, so I'll need to experiment. Hopefully they don't spaz out.

**Comment by ghost** [comment]
When you say tied to their own difficulty rating, would that mean that I can also add them in via Custom / Advanced difficulty? I really enjoy fine tuning my experience.

**Comment by Coolcord** [comment]
Yup! That's the plan!

I do think that'll be necessary, as with normal enemies, paratroopas, and flying cheep cheeps all on-screen at once, things might get pretty crazy.

**Comment by ghost** [comment]
Let me know when you got a new RC ready with the bug fix, eager to keep playing.

**Comment by Coolcord** [comment]
This issue should now be officially addressed with [the latest commit](https://github.com/Coolcord/Level-Headed/commit/a87390b898bd1f838b484e398128a17d0fca0db1).

I personally don't think the change is major enough to justify another RC, so these changes will be available when the stable build is released.

Thanks again for the bug report!

**Comment by ghost** [comment]
Welcome, glad to help. So far, so good. Really loving what it generated this time too.
